python train.py \
    --img-dir data/imagenette2-160 \
    --img-size 128 \
    --training-scheme supervised \
    --num-layers 18 \
    --epochs 1000 \
    --batch-size 64 \
    --lr 0.001 \
    --weight-decay 1e-6 \
    --output-dir exps/supervised/resnet18 \
    --gpu-idx 0